--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CupidonSauce173/PigraidNotifications
build-by-default: true
branches:
  - main
projects:
  PigNotify:
    path: ""
    icon: PigNotifIcon.png
...
